app = "backyardgarden"
primary_region = "sjc"

[build]

[env]
  PHX_HOST = "backyardgarden.fly.dev"
  PHX_SERVER = "true"
  DEFAULT_LOCATION = "Victoria,CA"
  ECTO_IPV6 = "true"

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]


[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
